### ISSUE TITLE
Overlay using up too much GPU

### ISSUE THREAD

**Issue by Wyzmic** [Blondazz/KeyOverlay#52]
![image](https://user-images.githubusercontent.com/72083780/208041800-fa803cbc-8ee2-4262-addb-d8423a119e1c.png)
For some reason, the key overlay is taking way too much of my GPU. I tried using older versions too, but the outcome is the same. Any ideas?

**Comment by Blondazz** [comment]
Is it after some time of usage or right away on start?

**Comment by Wyzmic** [comment]
> 
Does it right away.

**Comment by Blondazz** [comment]
Can you try the latest v1.0.4 release?

**Comment by Wyzmic** [comment]
> 

Thanks for updating it but still the same result. I tried the default settings too. Nothing else on my pc bugs out like this, it might be that the overlay doesn't work properly with the latest nvidia drivers. About 3 months ago this gpu usage problem wasn't a thing.
![image](https://user-images.githubusercontent.com/72083780/208325808-80a0c711-5792-48cb-ae99-eff094751110.png)

**Comment by Menotdan** [comment]
Huh, so that is weird, but I've seen GPU usage on my PC at 100% on the desktop, and I think it is because the GPU is clocked down really low, so the program is technically using a lot of GPU time but its just because the GPU isn't running at full speed. So, if 3 months ago when you checked, you had osu! open, your clocks would be higher because osu! renders at a high framerate.
